version: '1.0'
name: pipeline-20260122
displayName: x86_64
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-f044f367
    displayName: ci
    strategy: naturally
    trigger: manual
    executor:
      - lutaooooo
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: GCC 构建
        gccVersion: '9.4'
        commands:
          - 'cd build '
          - ./build.sh
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
