version: '1.0'
name: pipeline-linux
displayName: pipeline-linux
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-84e2f7a5
    displayName: Linux_x86_64编译
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: GCC 构建
        gccVersion: '9.4'
        commands:
          - '# 更新源并安装基础编译工具 + krb5开发库'
          - apt-get update && apt-get install -y \
          - '  gcc g++ make cmake \'
          - '  libkrb5-dev libssl-dev libcrypto++-dev \'
          - '  libutil-linux-dev librt-dev libdl-dev \'
          - '  binutils file coreutils'
          - '# 进入脚本所在目录（仓库根目录为工作目录）'
          - cd build
          - '# 执行编译脚本'
          - ./build_x86_64.sh
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
